#! python
# mcb.py- saves and restore text to the clipboard
''' Usage: py.exe mcb.pyw save <keyword>- saves clipboard text to keyword
           py.exe mcb.pyw <keyword>- restore keyword to clipboard
           py.exe mcb.pyw list- restore all keywords to clipboard '''
           
import shelve, pyperclip, sys

mcb_shelf = shelve.open('mcb')

# TODO: Save clipboard content
if len(sys.argv) == 3 and sys.argv[1].lower() == 'save':
    mcb_shelf[sys.argv[2]] = pyperclip.paste()
elif len(sys.argv) == 3 and sys.argv[1].lower() == 'delete':
    del mcb_shelf[sys.argv[2]]
elif len(sys.argv) == 2:
    # TODO: List keywords and restore content 
    if sys.argv[1].lower() == 'list':
        pyperclip.copy(str(list(mcb_shelf.keys())))
    elif sys.argv[1].lower() == 'delete':
        for keyword in list(mcb_shelf.keys()):
            del mcb_shelf[keyword]
    elif sys.argv[1] in mcb_shelf:
        pyperclip.copy(mcb_shelf[sys.argv[1]])


mcb_shelf.close()



       
